BLOG_COLLECTION: "blogs"
COMMENT_COLLECTION: "post_comments"
FOLLOW_COLLECTION: "follows"
BOOKMARK_COLLECTION: "bookmarks"
USER_INTEREST_COLLECTION: "userInterests"
DATABASE_NAME: "blogdb"
DATABASE_ADDRESS: "mongodb://localhost:27017"
PORT: ":8000"