BLOG_COLLECTION: "blogs"
COMMENT_COLLECTION: "post_comments"
FOLLOW_COLLECTION: "follows"
BOOKMARK_COLLECTION: "bookmarks"
USER_INTEREST_COLLECTION: "userInterests"
DATABASE_NAME: "blogdb"
DATABASE_ADDRESS: "mongodb+srv://dbUser:1q2w3e4r@oriscluster.uy936.mongodb.net"
PORT: ":8000"