basePath: /
consumes:
- application/json
definitions:
  CreatePostRequest:
    properties:
      article:
        type: string
        x-go-name: Article
      author:
        type: string
        x-go-name: Author
      categories:
        items:
          type: string
        type: array
        x-go-name: Categories
      status:
        type: string
        x-go-name: Status
      title:
        type: string
        x-go-name: Title
    title: CreatePostRequest represents body of CreatePost request.
    type: object
    x-go-package: blog/docs
  CreatePostResponse:
    properties:
      status:
        type: string
        x-go-name: PostID
    title: CreatePostResponse represents body of CreatePost response.
    type: object
    x-go-package: blog/docs
host: some-url.com
info:
  description: Documentation of Oris Blog API.
  title: Oris Blog.
  version: 1.0.0
paths: {}
produces:
- application/json
responses:
  CreatePostResponse:
    description: This text will appear as description of your response body.
    schema:
      $ref: '#/definitions/CreatePostResponse'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
